spring.application.name=SpringProjectTeam5

#SQL Server DataSource Setting
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=project2;encrypt=true;TrustServerCertificate=true
#spring.datasource.username=brenda
#spring.datasource.password=brenda

# PostgreSQL  
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 動態端口配置（Render要求）
server.port=${PORT:8080}

# 2025/10/7 100MB->10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Jackson åºååéç½®  é¿ååºååç©ºç Java Bean ç©ä»¶æå ±é¯
spring.jackson.serialization.fail-on-empty-beans=false
#Filter:Form->Put,Delete
spring.mvc.hiddenmethod.filter.enabled=true
# ??????????
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database=sql_server
spring.jpa.properties.hibernate.allow_update_outside_transaction=true

#WeatherApiKey
weather.api.key=${WEATHER_API_KEY}

# ??????
spring.jackson.time-zone=Asia/Taipei

# ?????????????
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


#upload File Setting
photo.storage.prefix=C:/Ispan/uploadImg/
video.storage.prefix=C:/Ispan/video/

# 新增Supabase配置
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_ANON_KEY}
supabase.storage.bucket=product-images
supabase.service.key=${SUPABASE_SERVICE_ROLE_KEY}
#-------------------------------------
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=TRACE
logging.level.org.springframework.security=DEBUG


spring.mail.host=smtp.gmail.com
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.port=${MAIL_PORT}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.transport.protocol=smtp
mail.display-name=Welcome to Inspire
verification.url=http://localhost:5174/


twilio.account.sid=${TWILIO_SID}
twilio.auth.token=${TWILIO_TOKEN}
twilio.phone.number=${TWILIO_PHONE}

#-----æå¡æ°å¢-----------
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#-----songæ°å¢-----------
spring.web.resources.static-locations=file:///Ispan/uploadImg/














